AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - features/**/*
    - .bundle/**/*
    - bundle_bin/**/*
    - lib/dwc_archive/ingester.rb
    - lib/dwc_archive/generator_meta_xml.rb
    - lib/dwc_archive/generator_eml_xml.rb
    - lib/dwc_archive/classification_normalizer.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '*.gemspec'
    - '**/*.rake'
    - 'spec/**/*spec.rb'
