rvm:
  - 1.9.3-p484
  - 2.0.0-p353
before_install:
  - sudo apt-get update
  - gem install debugger
# bundler_args: --without development
services:
  - redis-server
script:
  - bundle exec cucumber
  - bundle exec rake
branches:
  only:
      - master

