rvm:
  - 2.6
before_install:
  - sudo apt-get update
# bundler_args: --without development
services:
  - redis-server
script:
  - bundle exec cucumber
  - bundle exec rake
branches:
  only:
      - master

