rvm:
  - 2.0
  - 2.1
  - 2.2
before_install:
  - sudo apt-get update
# bundler_args: --without development
services:
  - redis-server
script:
  - gem install bundle
  - bundle exec cucumber
  - bundle exec rake
branches:
  only:
      - master

